repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: debug-statements
    -   id: detect-private-key
        exclude: auth/tests/unit/token_test.py
    # -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .(docker|git)ignore
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v1.9.1
    hooks:
    -   id: pylint
        args:
        - --max-line-length=80
        - --ignore-imports=yes
        - --disable=bad-whitespace,wrong-import-position,wrong-import-order,bad-continuation,unused-import
        - -d duplicate-code
        - -d fixme
        - -d import-error
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d too-few-public-methods
        - -d too-many-arguments
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/asottile/yesqa
    rev: v0.0.8
    hooks:
    -   id: yesqa
