version: 2.1

orbs:
  linter: thekevjames/linter@0.1

jobs:
  nox:
    docker:
      - image: thekevjames/nox:2018.10.17
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    parameters:
      folder:
        type: string
    steps:
      - run: apt-get -qy update && apt-get -qy install libssl-dev
      - run: echo ${GOOGLE_SERVICE_PUBLIC} | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: nox -f <<parameters.folder>>/noxfile.py

  pypi:
    docker:
      - image: python:3.7.0-slim
    steps:
      - run: pip install pyopenssl twine
      - checkout
      - deploy:
          name: upload to pypi
          command: |
            cd $(echo "${CIRCLE_TAG}" | sed 's/-.*//')
            python setup.py sdist bdist_wheel
            twine upload dist/*

  github:
    docker:
      - image: python:3.7.0-alpine3.8
    steps:
      - run: apk add --no-cache curl git openssh-client
      - checkout
      - run:
          name: install github-release
          command: |
            curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 > github-release.tar.bz2
            tar xjf github-release.tar.bz2
            rm -f github-release.tar.bz2
      - deploy:
          name: create GitHub release
          command: |
            export PROJECT=$(echo "${CIRCLE_TAG}" | sed 's/-.*//')
            export PREV_RELEASE=$(git tag --sort=version:refname | grep ${PROJECT} | tail -n2 | head -n1)
            [ "${PREV_RELEASE}" = "${CIRCLE_TAG}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)
            [ -z "${PREV_RELEASE}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)

            git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' > release-description.md
            ./bin/linux/amd64/github-release release -t "${CIRCLE_TAG}"
            cat release-description.md | grep ${PROJECT} | ./bin/linux/amd64/github-release edit -t ${CIRCLE_TAG} -d -

  py3to2:
    docker:
      - image: python:3.7.0-slim
    steps:
      - checkout
      - run: pip install pytest future strip-hints future-fstrings[rewrite]

      - run: find . -type f | grep "venv" | xargs -L1  -I"{}" rm -r  {} || true
      - run: find . -type f | grep ".pytest" | xargs -L1  -I"{}" rm -r  {} || true
      - run: find . -type f | grep "__pycache__" | xargs -L1  -I"{}" rm -r  {} || true

      - run: find . -exec dirname {} \; | grep "aio" | sed 's/aio/rest/g' | xargs -L1 mkdir -p
      - run: for file in $(find . -type f | grep "aio"); do cp -r $file $(echo "$file" | sed 's/aio/rest/g'); done
      - run: for file in $(find . -type f | grep "aio" | grep '\.py$' | sort | uniq); do new_file=$(echo "$file" | sed 's/aio/rest/g'); future-fstrings-show $file > $new_file; strip-hints $new_file > "${new_file}.tmp"; mv "${new_file}.tmp" $new_file; done
      - run: find . -type f | grep "aio" | xargs -L1 rm -r

      - run: find . -type f | xargs -L1 sed -Ei 's/gcloud\.aio/gcloud\.rest/g'
      - run: find . -type f | xargs -L1 sed -Ei 's/gcloud-aio/gcloud-rest/g'

      - run: find . -type f | grep '\.py$' | xargs -L1 pasteurize --nobackups --write

      - run: find . -type f | grep "requirements.txt" | xargs -L1 sed -Ei 's/aiohttp/#aiohttp/g'
      - run: find . -type f | grep -v "session.py" | xargs -L1 sed -Ei 's/AioSession/SyncSession/g'
      - run: find . -type f | xargs -L1 sed -Ei 's/(async|await) //g'
      - run: find . -type f | grep "tests/" | xargs -L1 sed -Ei 's/@pytest.mark.asyncio/#@pytest.mark.asyncio/g'

      - run: ls -al
      - persist_to_workspace:
          root: project
          paths:
          - ./*
  # old_nox1:
  #   docker:
  #     - image: thekevjames/nox:2019.5.30
  #   environment:
  #     GOOGLE_APPLICATION_CREDENTIALS: /key.json
  #   steps:
  #     - run: echo ${GOOGLE_SERVICE_PUBLIC} | base64 -d > ${GOOGLE_APPLICATION_CREDENTIALS}
  #     - checkout
  #     - run: nox
  # nox2:
  #   docker:
  #     - image: thekevjames/nox:2019.5.30
  #   environment:
  #     GOOGLE_APPLICATION_CREDENTIALS: /key.json
  #   parameters:
  #     folder:
  #       type: string
  #   steps:
  #     - run: echo ${GOOGLE_SERVICE_PUBLIC} | base64 -d > ${GOOGLE_APPLICATION_CREDENTIALS}
  #     - checkout
  #     - run: nox -f <<parameters.folder>>/noxfile.py


workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.6.6
          filters:
            tags:
              only: /.*/

      - nox:
          name: test-auth
          folder: auth
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-bigquery
          folder: bigquery
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-datastore
          folder: datastore
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-kms
          folder: kms
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-pubsub
          folder: pubsub
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-storage
          folder: storage
          filters:
            tags:
              only: /.*/
      - nox:
          name: test-taskqueue
          folder: taskqueue
          filters:
            tags:
              only: /.*/
      - py3to2:
          name: build-py2
          filters:
            tags:
              only: /.*/
          requires:
            - linter/pre-commit
            - test-auth
            # - test-bigquery
            # - test-datastore
            # - test-kms
            # - test-pubsub
            # - test-storage
            # - test-taskqueue


      - pypi:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[a-z]+-[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - test-auth
            - test-bigquery
            - test-datastore
            - test-kms
            - test-pubsub
            - test-storage
            - test-taskqueue
      - github:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[a-z]+-[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - test-auth
            - test-bigquery
            - test-datastore
            - test-kms
            - test-pubsub
            - test-storage
            - test-taskqueue
